config/routes.rb
Rails.application.routes.draw do
	root "articles#index"
	get "/articles", to: "articles#index"
	resources :articles
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
	#post '/articles/new', to: 'articles#new'
	#patch '/articles/:id', to: 'articles#update'
	#delete '/articles/:id', to: 'articles#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] # =|| конструкция работает по принципу посмотрим, что слева если там null выполни то, что справа и запиши результат в левую часть

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[update show destroy edit]
  def index
  	@articles = Article.all
  end
  def create
      article = Article.create(article_params)
      redirect_to article_path(article)

  end
  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article.destroy()
    redirect_to articles_path
  end
  def show
    @number_of_article = params[:id]
    @text_of_article = params[:body]
  end
  def new
    @article= Article.new do
    end
  end
  def edit
  end

  private

  def article_params
    params.require(:article).permit(:body, :id, :title)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user= User.find_by(email: user_params[:email])

    if user.present?
      session[:user_id]=user.id

      redirect_to root_path, notice: "Вы вошли на сайт!"
    else
      flash.now[:alert]="Неправильный email или пароль"

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: "Вы вышли из аккаунта!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end

  def create
      user_params = params.require(:user).permit(:name, :nickname, :email)

      User.create(user_params)

      redirect_to root_path, notice: "Регистрация прошла успешно"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div class="container">


<%= form_with model: article do |form| %>
  <p> <%= form.label :body, "Введите текст статьи" %></p>
  <p><%= form.text_area :body%></p>

  <p class="mt"><%= form.label :title, "Заголовок статьи" %></p>
  <p><%= form.text_field :title %></p>

  <p class="mt"><%= form.submit "Сохранить" %></p>
  <%= link_to "Назад", :back %>
<% end %>
</div>

app/views/articles/delete.html.erb
Статья успешно удалена

app/views/articles/edit.html.erb
<h3 class="title-lg white">Редактирование статьи: <%= @article.title %> </h3>
<%= render 'form', article: @article %>  <!--  Шаблон html был занесен в отдельных паршл _form ,  в паршл была передана переменная @article-->

app/views/articles/index.html.erb
<h1 class="title-lg white">Главная страница</h1>
<p class="mt">
  <%= link_to "Создать статью", "/articles/new" , class: 'button' %>
</p>
<div class="container mt">
  <% @articles.each do |article| %>
    <li class="mt-sm" >
      <%=link_to article.title, article_path(article.id) %>
    </li>
  <% end %>
</div>

app/views/articles/new.html.erb
<h3 class="title-lg">Новая статья</h3>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1 class="title-lg"> Это статья под номером <%= @number_of_article %> </h1>
<div class=container>
<p> <%= @article.body %></p>
<p><%= link_to "Назад к статьям", articles_path , class: 'button mt'%> </p>
<p> <%= link_to "Отредактировать статью", edit_article_path(@article) , class: 'button mt'%> </p>
<div class="">
  <%= button_to "Удалить статью", article_path(@article), method: :delete, class: 'button mt' %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<div class="wrapper">
  <header>
    <div class="navbar">
      <p> <%=link_to "Blog", root_path, class: "title-sm" %> </p>
      <div>
        <% if current_user.present? %>
          <%= content_tag 'span', " @#{current_user.nickname}", class:"mt-lg" %>
          <%= button_to 'Выйти', session_path, method: :delete , class:"button" %>
        <% else %>
          <%=link_to "Зарегистрироваться", new_user_path, class: "button" %>
          <%=link_to "Войти", new_session_path, class: "button" %>
        <% end %>
      </div>
    </div>
  </header>

    <% if flash[:notice].present? %>
      <p class="mb mt container"><%= flash[:notice]  %></p>
    <% elsif flash[:alert].present? %>
      <p class="mb mt container"><%= flash[:alert]  %></p>
      <% end %>

      <%= yield %>
</div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container wrapper-reg">
  <h2 class="title-lg"> Регистрация </h2>

  <div class="mt">
    <%= form_with model: @user do |form| %>
    <p> <%=form.label :name, "Ваше имя" %> </p>
    <p> <%=form.text_field :name, class: "form-text-field" %> </p>

    <p class=""> <%=form.label :nickname, "Имя профиля" %> </p>
    <p> <%=form.text_field :nickname, class: "form-text-field" %> </p>

    <p class=""> <%=form.label :email  %> </p>
    <p> <%=form.text_field :email, class: "form-text-field" %> </p>

    <p><%= form.submit 'Зарегистрироваться', class: 'button mt-sm'%> </p>
    <% end %>
  </div>
</div>